In [5]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import plot_tree

In [2]:
# Creating the dataset (same dataset used in ID3 example)

data = {
'Weather':['Sunny','Sunny','Cloudy','Rain','Rain','Rain','Cloudy','Sunny','Sunny','Rain','Sunny','Cloudy','Cloudy','Rain'],

'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],

'Humidity':['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],

'Wind':['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],

'PlayFootball':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Display dataset
df

   Weather Temperature Humidity    Wind PlayFootball
0    Sunny         Hot     High    Weak           No
1    Sunny         Hot     High  Strong           No
2   Cloudy         Hot     High    Weak          Yes
3     Rain        Mild     High    Weak          Yes
4     Rain        Cool   Normal    Weak          Yes
5     Rain        Cool   Normal  Strong           No
6   Cloudy        Cool   Normal  Strong          Yes
7    Sunny        Mild     High    Weak           No
8    Sunny        Cool   Normal    Weak          Yes
9     Rain        Mild   Normal    Weak          Yes
10   Sunny        Mild   Normal  Strong          Yes
11  Cloudy        Mild     High  Strong          Yes
12  Cloudy         Hot   Normal    Weak          Yes
13    Rain        Mild     High  Strong           No

In [6]:
df.head()

  Weather Temperature Humidity    Wind PlayFootball
0   Sunny         Hot     High    Weak           No
1   Sunny         Hot     High  Strong           No
2  Cloudy         Hot     High    Weak          Yes
3    Rain        Mild     High    Weak          Yes
4    Rain        Cool   Normal    Weak          Yes

In [7]:
df.describe()

       Weather Temperature Humidity  Wind PlayFootball
count       14          14       14    14           14
unique       3           3        2     2            2
top      Sunny        Mild     High  Weak          Yes
freq         5           6        7     8            9

In [13]:
le = LabelEncoder()
for col in df.columns:
    df[col] =le.fit_transform(df[col])
df

    Weather  Temperature  Humidity  Wind  PlayFootball
0         2            1         0     1             0
1         2            1         0     0             0
2         0            1         0     1             1
3         1            2         0     1             1
4         1            0         1     1             1
5         1            0         1     0             0
6         0            0         1     0             1
7         2            2         0     1             0
8         2            0         1     1             1
9         1            2         1     1             1
10        2            2         1     0             1
11        0            2         0     0             1
12        0            1         1     1             1
13        1            2         0     0             0

In [11]:
x = df.drop('PlayFootball',axis=1)
y=df['PlayFootball']
print("Feature (x):")
display(x)
print("Taeget (y):")
display(y)

Feature (x):

   Weather Temperature Humidity    Wind
0    Sunny         Hot     High    Weak
1    Sunny         Hot     High  Strong
2   Cloudy         Hot     High    Weak
3     Rain        Mild     High    Weak
4     Rain        Cool   Normal    Weak
5     Rain        Cool   Normal  Strong
6   Cloudy        Cool   Normal  Strong
7    Sunny        Mild     High    Weak
8    Sunny        Cool   Normal    Weak
9     Rain        Mild   Normal    Weak
10   Sunny        Mild   Normal  Strong
11  Cloudy        Mild     High  Strong
12  Cloudy         Hot   Normal    Weak
13    Rain        Mild     High  Strong

Taeget (y):

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: PlayFootball, dtype: object

In [21]:
model=DecisionTreeClassifier(criterion='entropy')
model.fit(x,y)
print("model Trained sucessfull")

ValueError: could not convert string to float: 'Sunny'

In [20]:
sample -[[2,0,0,1]]
prediction = model.predict(simple)
print("prediction:",predicition)

NameError: name 'sample' is not defined

In [18]:
plt.figure(figsize=(18,10))
plot_tree(
    model,
    feature_names=X.columns,
    class_names=['No','Yes'],
    filled=True,
    rounded=True,
    fontsize=12
)
plt.title("Decision Tree using ID3 Algorithm")
plt.show()

NameError: name 'X' is not defined